### ISSUE TITLE
Support for 1122334455667788 NetNTLM challenge

### ISSUE THREAD

**Issue by ss23** [s0lst1c3/eaphammer#126]
Currently, NetNTLM hashes from a EAP attack (e.g. `./eaphammer --bssid 1C:7E:E5:97:79:B1 --essid example --channel 2 --interface wlan0 --auth wpa-eap --creds`) have a randomly generated challenge.

To aid in cracking (such as with http://crack.sh), a challenge of 1122334455667788 would be preferred in some cases.

I would like to see the option to specify a custom challenge implemented to allow this.

**Comment by s0lst1c3** [comment]
Hi @ss23, 

Although intuitively it seems this proposed technique should work, it's actually not possible since MSCHAPv2 uses both client and server nonces to create the challenge hash. Please see the following response to a similar feature request for a more detailed explanation:

https://github.com/s0lst1c3/eaphammer/issues/64

Thanks!
