### ISSUE TITLE
how to prevent the conf from being overwritten?

### ISSUE THREAD

**Issue by jackassplus** [s0lst1c3/eaphammer#16]
I'm trying to enable 802.11n but overtime I enable 802.11n, save the config and restart, it changes it back.

**Comment by s0lst1c3** [comment]
EAPHammer actually generates configuration files dynamically each time the tool is run, based on whatever command line arguments are provided by the user. That's why the configs are being overwritten.

Ideally, enabling 802.11n would be just a matter of passing the appropriate flags at startup, but I haven't actually added 802.11n support to the tool yet. It's something that I'm planning in the next month or so, but if you want to try your hand at it and make a pull request I totally encourage you to do so.

**Comment by jackassplus** [comment]
802.11n/ac is principally constructed from edge cases. I have a config that works for some channels with a specific radio. It would be smoother to use sed and/or the regex classes to modify the config rather than template it.

**Comment by s0lst1c3** [comment]
I've gone down the sed/regex path before, didn't lead anywhere great. A couple of suggestions though, which may or may not be relevant depending on what your use case is.

First suggestion: just make an 802.11g access point, then use bursts of deauth packets to prevent clients from associating with the target access points (which presumably are using 802.11n or 802.11ac). The only time I have seen this attack fail is against a network that was protected by Cisco Air Marshall, which seems to flag this kind of activity in seconds. Even then, the solution is to tail an employee outside of the building and then perform the rogue AP there, since the WIPS won't be much of a mitigating factor at that point. This is a edge case though.

Second idea: would it help you if I added a --manual flag that lets you specify a custom config file?

**Comment by wytshadow** [comment]
"Second idea: would it help you if I added a --manual flag that lets you specify a custom config file?"

yes please.

**Comment by s0lst1c3** [comment]
@wytshadow @jackassplus - Hey, sorry this took so long. My consulting schedule got the better of me during the last few months. I've expanded the existing command line options, added the ability to load and save config files, and added support for 802.11n (802.11ac soon to come). Let me know what you think.
