### ISSUE TITLE
Openssl Error

### ISSUE THREAD

**Issue by nm8800** [s0lst1c3/eaphammer#48]
I am receiving the following here if I run eaphammer with the following command:

eaphammer --interface wlan1 --essid Fuck --auth wpa --hostile-portal --karma

this works on a windows 10, it passes the NetNTLM hash but it doesn't work from my phone or windows 7 desktop

The error is:

> OpenSSL: openssl_handshake - SSL_connect error:14209102:SSL routines:tls_early_post_process_client_hello:supported protocol.

I'm thinking this may be something to do with lack of TLS?

The windows 10 is connected to a domain FYI

**Comment by s0lst1c3** [comment]
I've seen this before too, and it's something that is currently in the pipeline to be addressed. It's actually a problem related to OpenSSL rather than EAPHammer itself, but arguably something that tools like EAPHammer should be able to contend with. Allow me to explain.

Long story short: when a client device authenticates with a WPA/2-EAP access point created by EAPHammer (or any other AP for that matter), in most cases it's going to need to establish a secure tunnel to the AP through which to pass data. In order to support this functionality, both the client and the AP will likely rely on OpenSSL.

OpenSSL itself is highly configureable: you can select which versions of SSL and TLS to support, as well as which cipher suites to allow. The problem is that a lot of these configuration options are insecure, particularly the ones that allow communication using older cipher suites and protocol versions.

SSL versions 2 and 3 are particularly problematic, as they both suffer from some pretty serious cryptographic weaknesses. The problems that affect SSL versions 2 and 3 are serious enough that support for these versions has been explicitly removed from the latest versions of OpenSSL. You actually have to recompile the library if you want to support them. As a result, modern operating systems such as Windows 10 and the latest versions of Kali will refuse to communicate with systems that use SSLv2 or SSLv3.

My guess is that your Windows 7 desktop is trying to communicate with your rogue AP using SSLv3. This is causing the connection to fail, because SSLv3 is probably not supported by the system that's running EAPHammer. Your phone may be attempting to do this as well, depending on its age.

You could try recompiling OpenSSL to support version 3, although this may make it impossible to communicate with newer devices. It's a trade off. Ideally, from a pentester's perspective, it makes sense to be able to easily switch between different OpenSSL configurations in order to support both new and legacy devices. There isn't really a clean or easy way of doing that right now, but rest assured it's a problem I'm personally invested in solving since it actually has an impact on my day job. 

P.S.: be careful with the --karma flag if you're just messing around. EAPHammer doesn't currently a way of preventing nearby devices that aren't your intended target from connecting to you. Make sure you run the whole operation from a box wrapped in tinfoil or something.

**Comment by nm8800** [comment]
Thank you for the response, I too use this tool for day job. I have only recently been introduced to it. I figured Karma was going to force other devices to connect, but that was my intention as I was operating at a corporate office where the ROE specified this. 

In the middle of my test I noticed a lot of different machines wanting to connect to the Evil Twin but wouldn't send any hashes due to what was mentioned above. I'm glad to have a better understanding of the problem. Thank you so much.
