### ISSUE TITLE
Feature Request: Fixed MS-CHAPv2 Challenges (orig: Fixed Challenge to 11:22:33:44:55:66:77:88 eap)

### ISSUE THREAD

**Issue by T3KX** [s0lst1c3/eaphammer#64]
Hi 
Would it be possible to set a fixed challenge for eap to 11:22:33:44:55:66:77:88 ?

I believe it would help to crack the netntlmv1 .

Thanks

**Comment by T3KX** [comment]
for example , this service do netntlmv1 for free if the chal is set to this
https://crack.sh/netntlm/

**Comment by illera88** [comment]
Yes, this would be very useful to later use rainbow tables

**Comment by s0lst1c3** [comment]
This is an awesome idea and will definitely be added to the project.

**Comment by s0lst1c3** [comment]
It turns out that implementing this is impossible. Even though it’s possible to convert an MSCHAPv2 ChallengeHash and Response pair into an NTLM hash, it’s important to remember that NTLM and MSCHAPv2 are not the same protocol. Unlike what we see in NTLM, the MSCHAPv2 ChallengeHash contains random challenges (nonces) from both the client and the server (see diagram below). We can only control what happens on the server’s side of the transaction, and as such cannot control the value of the ChallengeHash.

If you want to examine this process in depth, I recommend checking this article out:

https://sensepost.com/blog/2019/understanding-peap-in-depth/

Cheers.
