### ISSUE TITLE
Use kali package

### ISSUE THREAD

**Issue by evs-pn** [s0lst1c3/eaphammer#7]
Hello,

i want to ask why you not use the existing hostapd-wpe implementation that is already packed in the kali repos? 
Checkout: http://tools.kali.org/wireless-attacks/hostapd-wpe

Best regards,
Cheers!

**Comment by s0lst1c3** [comment]
Hey there. To start out with, I just want to say that the original hostapd-wpe is a great tool that was way ahead of its time when it was released. With that said, the tweaks I’ve made to it deviate far enough from the original project that it makes more sense to operate from my own standalone git repository. Specifically, I’ve completely removed the Cupid and Karma modules. The Cupid module is non-essential to the functionality offered by eaphammer, and requires an older version of OpenSSL to function. This makes the project unnecessarily difficult to compile and causes compatibility issues with newer wireless supplicants. When harvesting RADIUS creds from a WPA2-EAP network, it’s important to cast as wide a net as possible. As such, I’d rather maximize compatibility with wireless supplicants than support an extra feature that allows the tool to test for Heartbleed. As for the Karma module, it was great when it was released. However, it isn't nearly as effective at performing Karma attacks as modern tools such Sensepost’s hostapd-mana. Since the design objectives of eaphammer vary considerably from that of Mana, I don’t see a reason to add extra complexity by including this component. There are a few other significant changes that are in the works, but I don’t really want to discuss them here yet. Hope that clears things up a bit. Cheers.
