### ISSUE TITLE
Supplying Wifi from Wlan0 to Evil AP

### ISSUE THREAD

**Issue by JavaRockstar** [s0lst1c3/eaphammer#8]
I'm trying to use EAPHammer its working fine although I cant get a bridge between my Internet source and the Evil AP I'm using an Internal Wifi card connected to a mobile hotspot to access the net.

wlan2 is my evil AP card that supports master mode.

When I run EAPHammer I get disconnected from my main access point and NetworkManager shuts down and the EvilAP is started. I'm using Kali Linux 2017 

I'm trying to use the Captive Portal Attack and inject a fake HTML page via DNS without internet access the DNS does not seem to spoof when connecting to the Mobile Hotspot my local IP becomes 192.168.42.49 and I wondered if EAPHammer was looking for a different IP range.

When I close EAPHammer I use commands service NetworkManager restart and my Internal Wifi connection is restored.

Ideally I'd like to bridge or route wlan0 (Internet connected device running in NetworkManager)
and route it to the evil AP that is listed under wlan2 of my system. or to be able to set a bridge from wlan0 (Internet source) to eth0 then to the Evil AP.
 
Has anyone has any experience with this problem and be kind enough to point out where I'm going wrong.

**Comment by s0lst1c3** [comment]
Hey @JavaRockstar JavaRockstar,

Thanks for checking out EAPHammer. As of right now, EAPHammer doesn’t support the ability to perform a MITM attack by bridging hostapd’s interface with an upstream interface connected to an internet gateway. It sounds like that’s what you’re trying to do. With that said, this is a feature that I planned on adding in the near future, and since you’ve expressed interest in it I’m going to move this feature to the front of the queue and try to finish it within the next couple of weeks.

> When I run EAPHammer I get disconnected from my main access point and NetworkManager shuts down and the EvilAP is started. I'm using Kali Linux 201

If I understand correctly, you’re trying to connect your upstream interface (upstream == the interface that’s connected to your hotspot) before starting EAPHammer. The problem with this is that when EAPHammer first starts, it shuts down any services or processes that could interfere with hostapd’s ability to create an access point. These interfering processes include NetworkManager. When NetworkManager is stopped, the process first disables all of your wireless interfaces before terminating, which will cause you to lose your connection to your wireless hotspot. There are workarounds for this, but they’re all fairly complicated to do by hand. For now, my advice would be to use your wired interface (eth0) as the upstream interface. To do this, establish an Ethernet connection, then start EAPHammer, then run the following commands:

```
	ifconfig eth0 up
	dhclient eth0
```

You’ll still have to use iptables or similar to bridge the two networks together.
 

> I'm trying to use the Captive Portal Attack and inject a fake HTML page via DNS without internet access the DNS does not seem to spoof when connecting to the Mobile Hotspot my local IP becomes 192.168.42.49 and I wondered if EAPHammer was looking for a different IP range. 

As of right now, EAPHammer only supports Captive Portals as a noupstream attack. The IP address of the access point is automatically set to 10.0.0.1. The IP range is set to 10.0.0.0/24. It sounds like I need to add a command line flag that lets users specify their access point’s IP range manually, so I’m going to go ahead and do that.

> Ideally I'd like to bridge or route wlan0 (Internet connected device running in NetworkManager) and route it to the evil AP that is listed under wlan2 of my system. or to be able to set a bridge from wlan0 (Internet source) to eth0 then to the Evil AP.

You’ll be able to do that in the next couple of weeks or so. ;) This is still a pretty new tool so I haven’t had the chance to add that functionality yet.

**Comment by JavaRockstar** [comment]
Thanks for your reply and really good work with the EAPHammer project that would be great adding a input for users to specify there upstream address I really love how its command line based and not to graphical makes life real simple using the command line.

I had an idea a feature that could pick up device probes, find what AP the device is looking for a make a clone of the best possible match. Ive been using tools like Snoopy to capture the full range of AP the devices are looking for and saving them to a sql database as I was using airodump-ng and it told very limited probe information.

Another idea would be to capture all data and send it to a remote location in the cloud or a private web server to view remotely away from the Evil Access Point.

Thanks for your time keep up the good work. :)

**Comment by JavaRockstar** [comment]
The problem with this is that when EAPHammer first starts, it shuts down any services or processes that could interfere with hostapd’s ability to create an access point.

I've seen this happening with a lot of tools I was told there a few tricks to get past it the only thing your tool is lacking is this feature I see a lot trying to integrate this feature theres a tool called airgeddon that seems to have solved the issue I still cant get it working on this side though maybes you could take a look at there script for a few ideas it uses hostap lighttpd iptables isc-dhcp-server thanks in advance I hope its ok to share another tool here its just to give your an idea of something similar why I like you tool is that it supports the corporate wifi and its very easy to set up and real simple captive portal method.

**Comment by s0lst1c3** [comment]
Hi @JavaRockstar, thanks for the feedback. I'll look into ways of preventing network-manager and wpa_supplicant from interfering with hostapd, without killing the processes completely. I am going to have to put this feature request on the backburner for at least a month or so, since there are other features that need to be implemented during that time period. Stay tuned though!

**Comment by s0lst1c3** [comment]
Resolved by 78fa673be9dcf132b3c5e37dbcb04fceb8135e63.
